### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by bbinet** [martinhoefling/molten#28]
```
$ npm install

> history@1.12.5 postinstall /home/bruno/dev/3rd/molten/node_modules/history
> node npm-scripts/postinstall.js

npm WARN unmet dependency /home/bruno/dev/3rd/molten/node_modules/babel-jest requires babel-core@'^5.5.7' but will load
npm WARN unmet dependency /home/bruno/dev/3rd/molten/node_modules/babel-core,
npm WARN unmet dependency which is version 6.4.0
npm ERR! Linux 3.16.0-0.bpo.4-amd64
npm ERR! argv "/home/bruno/.virtualenvs/nodeenv/bin/node" "/home/bruno/.virtualenvs/nodeenv/bin/npm" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package history@1.12.5 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router@1.0.3 wants history@^1.17.0

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bruno/dev/3rd/molten/npm-debug.log
```

`npm-debug.log` file contains:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/bruno/.virtualenvs/nodeenv/bin/node',
1 verbose cli   '/home/bruno/.virtualenvs/nodeenv/bin/npm',
1 verbose cli   'install' ]
2 info using npm@2.14.4
3 info using node@v4.1.2
4 verbose readDependencies loading dependencies from /home/bruno/dev/3rd/molten/package.json
5 verbose install where, deps [ '/home/bruno/dev/3rd/molten',
5 verbose install   [ 'classnames',
5 verbose install     'fbjs',
5 verbose install     'lodash',
5 verbose install     'material-ui',
5 verbose install     'moment',
5 verbose install     'react',
5 verbose install     'react-dom',
5 verbose install     'react-redux',
5 verbose install     'react-router',
5 verbose install     'react-shortcuts',
5 verbose install     'react-tap-event-plugin',
5 verbose install     'react-toastr',
5 verbose install     'redux',
5 verbose install     'redux-devtools',
5 verbose install     'redux-logger',
5 verbose install     'redux-router',
5 verbose install     'redux-thunk',
5 verbose install     'reselect',
5 verbose install     'superagent',
5 verbose install     'babel-core',
5 verbose install     'babel-eslint',
5 verbose install     'babel-loader',
5 verbose install     'babel-polyfill',
5 verbose install     'babel-preset-es2015',
5 verbose install     'babel-preset-react',
5 verbose install     'css-loader',
5 verbose install     'eslint',
5 verbose install     'eslint-loader',
5 verbose install     'eslint-plugin-react',
5 verbose install     'esprima-fb',
5 verbose install     'extract-text-webpack-plugin',
5 verbose install     'http-server',
5 verbose install     'jasmine-ajax',
5 verbose install     'jasmine-core',
5 verbose install     'jscs',
5 verbose install     'karma',
5 verbose install     'karma-chrome-launcher',
5 verbose install     'karma-firefox-launcher',
5 verbose install     'karma-jasmine',
5 verbose install     'karma-jasmine-ajax',
5 verbose install     'karma-sourcemap-loader',
5 verbose install     'karma-webpack',
5 verbose install     'less',
5 verbose install     'less-loader',
5 verbose install     'node-libs-browser',
5 verbose install     'redux-devtools-dock-monitor',
5 verbose install     'redux-devtools-log-monitor',
5 verbose install     'redux-persist',
5 verbose install     'style-loader',
5 verbose install     'underscore.string',
5 verbose install     'webpack',
5 verbose install     'webpack-dev-server' ] ]
6 verbose install where, peers [ '/home/bruno/dev/3rd/molten', [] ]
7 verbose installManyTop reading for lifecycle /home/bruno/dev/3rd/molten/package.json
8 info preinstall molten@0.1.0
9 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/babel-core/package.json
10 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/babel-eslint/package.json
11 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/babel-jest/package.json
12 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/babel-loader/package.json
13 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/babel-polyfill/package.json
14 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/babel-preset-es2015/package.json
15 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/babel-preset-react/package.json
16 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/classnames/package.json
17 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/css-loader/package.json
18 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/eslint/package.json
19 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/eslint-loader/package.json
20 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/eslint-plugin-react/package.json
21 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/esprima-fb/package.json
22 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/extract-text-webpack-plugin/package.json
23 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/fbjs/package.json
24 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/fluxxor/package.json
25 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/history/package.json
26 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/http-server/package.json
27 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/jasmine-ajax/package.json
28 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/jasmine-core/package.json
29 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/jest-cli/package.json
30 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/jscs/package.json
31 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/karma/package.json
32 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/karma-chrome-launcher/package.json
33 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/karma-firefox-launcher/package.json
34 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/karma-jasmine/package.json
35 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/karma-jasmine-ajax/package.json
36 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/karma-sourcemap-loader/package.json
37 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/karma-webpack/package.json
38 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/less/package.json
39 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/less-loader/package.json
40 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/lodash/package.json
41 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/material-ui/package.json
42 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/moment/package.json
43 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/node-libs-browser/package.json
44 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/react/package.json
45 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/react-dom/package.json
46 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/react-redux/package.json
47 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/react-router/package.json
48 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/react-shortcuts/package.json
49 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/react-tap-event-plugin/package.json
50 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/react-toastr/package.json
51 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/redux/package.json
52 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/redux-devtools/package.json
53 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/redux-devtools-dock-monitor/package.json
54 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/redux-devtools-log-monitor/package.json
55 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/redux-logger/package.json
56 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/redux-persist/package.json
57 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/redux-router/package.json
58 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/redux-thunk/package.json
59 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/reselect/package.json
60 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/style-loader/package.json
61 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/superagent/package.json
62 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/underscore.string/package.json
63 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/webpack/package.json
64 verbose installManyTop reading scoped package data from /home/bruno/dev/3rd/molten/node_modules/webpack-dev-server/package.json
65 info package.json babel-jest@5.3.0 No license field.
66 info package.json babel-polyfill@6.3.14 No description
67 info package.json esprima-fb@15001.1001.0-dev-harmony-fb No license field.
68 info package.json less-loader@2.2.1 No license field.
69 info package.json react-tap-event-plugin@0.2.1 No license field.
70 verbose readDependencies loading dependencies from /home/bruno/dev/3rd/molten/package.json
71 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/babel-core/package.json
72 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/babel-eslint/package.json
73 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/babel-jest/package.json
74 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/babel-loader/package.json
75 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/babel-polyfill/package.json
76 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/babel-preset-es2015/package.json
77 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/babel-preset-react/package.json
78 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/classnames/package.json
79 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/css-loader/package.json
80 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/eslint/package.json
81 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/eslint-loader/package.json
82 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/eslint-plugin-react/package.json
83 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/esprima-fb/package.json
84 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/extract-text-webpack-plugin/package.json
85 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/fbjs/package.json
86 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/fluxxor/package.json
87 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/history/package.json
88 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/http-server/package.json
89 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/jasmine-ajax/package.json
90 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/jasmine-core/package.json
91 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/jest-cli/package.json
92 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/jscs/package.json
93 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/karma/package.json
94 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/karma-chrome-launcher/package.json
95 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/karma-firefox-launcher/package.json
96 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/karma-jasmine/package.json
97 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/karma-jasmine-ajax/package.json
98 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/karma-sourcemap-loader/package.json
99 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/karma-webpack/package.json
100 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/less/package.json
101 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/less-loader/package.json
102 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/lodash/package.json
103 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/material-ui/package.json
104 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/moment/package.json
105 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/node-libs-browser/package.json
106 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/react/package.json
107 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/react-dom/package.json
108 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/react-redux/package.json
109 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/react-router/package.json
110 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/react-shortcuts/package.json
111 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/react-tap-event-plugin/package.json
112 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/react-toastr/package.json
113 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/redux/package.json
114 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/redux-devtools/package.json
115 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/redux-devtools-dock-monitor/package.json
116 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/redux-devtools-log-monitor/package.json
117 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/redux-logger/package.json
118 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/redux-persist/package.json
119 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/redux-router/package.json
120 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/redux-thunk/package.json
121 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/reselect/package.json
122 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/style-loader/package.json
123 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/superagent/package.json
124 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/underscore.string/package.json
125 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/webpack/package.json
126 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/webpack-dev-server/package.json
127 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/.bin/eslint/package.json
128 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/.bin/esparse/package.json
129 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/.bin/esvalidate/package.json
130 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/.bin/hs/package.json
131 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/.bin/http-server/package.json
132 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/.bin/jest/package.json
133 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/.bin/jscs/package.json
134 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/.bin/karma/package.json
135 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/.bin/lessc/package.json
136 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/.bin/webpack/package.json
137 verbose targetResolver reading package data from /home/bruno/dev/3rd/molten/node_modules/.bin/webpack-dev-server/package.json
138 verbose already installed skipping node-libs-browser@^0.5.3 /home/bruno/dev/3rd/molten
139 verbose already installed skipping redux-devtools-dock-monitor@^1.0.1 /home/bruno/dev/3rd/molten
140 verbose already installed skipping redux-devtools-log-monitor@^1.0.1 /home/bruno/dev/3rd/molten
141 verbose already installed skipping redux-persist@^1.5.0 /home/bruno/dev/3rd/molten
142 verbose already installed skipping style-loader@^0.13.0 /home/bruno/dev/3rd/molten
143 verbose already installed skipping underscore.string@^3.2.2 /home/bruno/dev/3rd/molten
144 verbose already installed skipping webpack@^1.12.6 /home/bruno/dev/3rd/molten
145 verbose already installed skipping webpack-dev-server@^1.14.0 /home/bruno/dev/3rd/molten
146 verbose already installed skipping classnames@^2.2.1 /home/bruno/dev/3rd/molten
147 verbose already installed skipping fbjs@^0.6.0 /home/bruno/dev/3rd/molten
148 verbose already installed skipping lodash@^3.10.1 /home/bruno/dev/3rd/molten
149 verbose already installed skipping material-ui@^0.14.1 /home/bruno/dev/3rd/molten
150 verbose already installed skipping moment@^2.10.6 /home/bruno/dev/3rd/molten
151 verbose already installed skipping react@^0.14.3 /home/bruno/dev/3rd/molten
152 verbose already installed skipping react-dom@^0.14.3 /home/bruno/dev/3rd/molten
153 verbose already installed skipping react-redux@^4.0.0 /home/bruno/dev/3rd/molten
154 verbose already installed skipping react-router@^1.0.0 /home/bruno/dev/3rd/molten
155 verbose already installed skipping react-shortcuts@^0.7.3 /home/bruno/dev/3rd/molten
156 verbose already installed skipping react-tap-event-plugin@^0.2.1 /home/bruno/dev/3rd/molten
157 verbose already installed skipping react-toastr@^2.2.2 /home/bruno/dev/3rd/molten
158 verbose already installed skipping redux@^3.0.4 /home/bruno/dev/3rd/molten
159 verbose already installed skipping redux-devtools@^3.0.1 /home/bruno/dev/3rd/molten
160 verbose already installed skipping redux-logger@^2.0.4 /home/bruno/dev/3rd/molten
161 verbose already installed skipping redux-router@^1.0.0-beta5 /home/bruno/dev/3rd/molten
162 verbose already installed skipping redux-thunk@^1.0.0 /home/bruno/dev/3rd/molten
163 verbose already installed skipping reselect@^2.0.1 /home/bruno/dev/3rd/molten
164 verbose already installed skipping superagent@^1.4.0 /home/bruno/dev/3rd/molten
165 verbose already installed skipping babel-core@^6.2.4 /home/bruno/dev/3rd/molten
166 verbose already installed skipping babel-eslint@^4.1.6 /home/bruno/dev/3rd/molten
167 verbose already installed skipping babel-loader@^6.2.0 /home/bruno/dev/3rd/molten
168 verbose already installed skipping babel-polyfill@^6.3.14 /home/bruno/dev/3rd/molten
169 verbose already installed skipping babel-preset-es2015@^6.2.4 /home/bruno/dev/3rd/molten
170 verbose already installed skipping babel-preset-react@^6.2.4 /home/bruno/dev/3rd/molten
171 verbose already installed skipping css-loader@^0.23.0 /home/bruno/dev/3rd/molten
172 verbose already installed skipping eslint@^1.9.0 /home/bruno/dev/3rd/molten
173 verbose already installed skipping eslint-loader@^1.1.1 /home/bruno/dev/3rd/molten
174 verbose already installed skipping eslint-plugin-react@^3.11.1 /home/bruno/dev/3rd/molten
175 verbose already installed skipping esprima-fb@^15001.1001.0-dev-harmony-fb /home/bruno/dev/3rd/molten
176 verbose already installed skipping extract-text-webpack-plugin@^0.9.1 /home/bruno/dev/3rd/molten
177 verbose already installed skipping http-server@^0.8.5 /home/bruno/dev/3rd/molten
178 verbose already installed skipping jasmine-ajax@^3.2.0 /home/bruno/dev/3rd/molten
179 verbose already installed skipping jasmine-core@^2.3.4 /home/bruno/dev/3rd/molten
180 verbose already installed skipping jscs@^2.5.1 /home/bruno/dev/3rd/molten
181 verbose already installed skipping karma@^0.13.15 /home/bruno/dev/3rd/molten
182 verbose already installed skipping karma-chrome-launcher@^0.2.1 /home/bruno/dev/3rd/molten
183 verbose already installed skipping karma-firefox-launcher@^0.1.7 /home/bruno/dev/3rd/molten
184 verbose already installed skipping karma-jasmine@^0.3.6 /home/bruno/dev/3rd/molten
185 verbose already installed skipping karma-jasmine-ajax@^0.1.13 /home/bruno/dev/3rd/molten
186 verbose already installed skipping karma-sourcemap-loader@^0.3.6 /home/bruno/dev/3rd/molten
187 verbose already installed skipping karma-webpack@^1.7.0 /home/bruno/dev/3rd/molten
188 verbose already installed skipping less@^2.5.3 /home/bruno/dev/3rd/molten
189 verbose already installed skipping less-loader@^2.2.1 /home/bruno/dev/3rd/molten
190 silly install resolved []
191 info build /home/bruno/dev/3rd/molten
192 info linkStuff molten@0.1.0
193 silly linkStuff molten@0.1.0 has /home/bruno/dev/3rd as its parent node_modules
194 verbose linkBins molten@0.1.0
195 verbose linkMans molten@0.1.0
196 verbose rebuildBundles molten@0.1.0
197 verbose rebuildBundles [ '.bin',
197 verbose rebuildBundles   'babel-core',
197 verbose rebuildBundles   'babel-eslint',
197 verbose rebuildBundles   'babel-jest',
197 verbose rebuildBundles   'babel-loader',
197 verbose rebuildBundles   'babel-polyfill',
197 verbose rebuildBundles   'babel-preset-es2015',
197 verbose rebuildBundles   'babel-preset-react',
197 verbose rebuildBundles   'classnames',
197 verbose rebuildBundles   'css-loader',
197 verbose rebuildBundles   'eslint',
197 verbose rebuildBundles   'eslint-loader',
197 verbose rebuildBundles   'eslint-plugin-react',
197 verbose rebuildBundles   'esprima-fb',
197 verbose rebuildBundles   'extract-text-webpack-plugin',
197 verbose rebuildBundles   'fbjs',
197 verbose rebuildBundles   'fluxxor',
197 verbose rebuildBundles   'history',
197 verbose rebuildBundles   'http-server',
197 verbose rebuildBundles   'jasmine-ajax',
197 verbose rebuildBundles   'jasmine-core',
197 verbose rebuildBundles   'jest-cli',
197 verbose rebuildBundles   'jscs',
197 verbose rebuildBundles   'karma',
197 verbose rebuildBundles   'karma-chrome-launcher',
197 verbose rebuildBundles   'karma-firefox-launcher',
197 verbose rebuildBundles   'karma-jasmine',
197 verbose rebuildBundles   'karma-jasmine-ajax',
197 verbose rebuildBundles   'karma-sourcemap-loader',
197 verbose rebuildBundles   'karma-webpack',
197 verbose rebuildBundles   'less',
197 verbose rebuildBundles   'less-loader',
197 verbose rebuildBundles   'lodash',
197 verbose rebuildBundles   'material-ui',
197 verbose rebuildBundles   'moment',
197 verbose rebuildBundles   'node-libs-browser',
197 verbose rebuildBundles   'react',
197 verbose rebuildBundles   'react-dom',
197 verbose rebuildBundles   'react-redux',
197 verbose rebuildBundles   'react-router',
197 verbose rebuildBundles   'react-shortcuts',
197 verbose rebuildBundles   'react-tap-event-plugin',
197 verbose rebuildBundles   'react-toastr',
197 verbose rebuildBundles   'redux',
197 verbose rebuildBundles   'redux-devtools',
197 verbose rebuildBundles   'redux-devtools-dock-monitor',
197 verbose rebuildBundles   'redux-devtools-log-monitor',
197 verbose rebuildBundles   'redux-logger',
197 verbose rebuildBundles   'redux-persist',
197 verbose rebuildBundles   'redux-router',
197 verbose rebuildBundles   'redux-thunk',
197 verbose rebuildBundles   'reselect',
197 verbose rebuildBundles   'style-loader',
197 verbose rebuildBundles   'superagent',
197 verbose rebuildBundles   'underscore.string',
197 verbose rebuildBundles   'webpack',
197 verbose rebuildBundles   'webpack-dev-server' ]
198 verbose rebuild bundle /home/bruno/dev/3rd/molten/node_modules/babel-jest
199 info build /home/bruno/dev/3rd/molten/node_modules/babel-jest
200 info preinstall babel-jest@5.3.0
201 info linkStuff babel-jest@5.3.0
202 silly linkStuff babel-jest@5.3.0 has /home/bruno/dev/3rd/molten/node_modules as its parent node_modules
203 verbose linkBins babel-jest@5.3.0
204 verbose linkMans babel-jest@5.3.0
205 verbose rebuildBundles babel-jest@5.3.0
206 info install babel-jest@5.3.0
207 info postinstall babel-jest@5.3.0
208 verbose rebuild bundle /home/bruno/dev/3rd/molten/node_modules/fluxxor
209 info build /home/bruno/dev/3rd/molten/node_modules/fluxxor
210 info preinstall fluxxor@1.7.3
211 info linkStuff fluxxor@1.7.3
212 silly linkStuff fluxxor@1.7.3 has /home/bruno/dev/3rd/molten/node_modules as its parent node_modules
213 verbose linkBins fluxxor@1.7.3
214 verbose linkMans fluxxor@1.7.3
215 verbose rebuildBundles fluxxor@1.7.3
216 verbose rebuildBundles [ 'eventemitter3', 'object-path' ]
217 info install fluxxor@1.7.3
218 info postinstall fluxxor@1.7.3
219 verbose rebuild bundle /home/bruno/dev/3rd/molten/node_modules/history
220 info build /home/bruno/dev/3rd/molten/node_modules/history
221 info preinstall history@1.12.5
222 info linkStuff history@1.12.5
223 silly linkStuff history@1.12.5 has /home/bruno/dev/3rd/molten/node_modules as its parent node_modules
224 verbose linkBins history@1.12.5
225 verbose linkMans history@1.12.5
226 verbose rebuildBundles history@1.12.5
227 verbose rebuildBundles [ 'deep-equal', 'invariant', 'qs', 'warning' ]
228 info install history@1.12.5
229 info postinstall history@1.12.5
230 verbose unsafe-perm in lifecycle true
231 verbose rebuild bundle /home/bruno/dev/3rd/molten/node_modules/jest-cli
232 info build /home/bruno/dev/3rd/molten/node_modules/jest-cli
233 info preinstall jest-cli@0.5.10
234 info linkStuff jest-cli@0.5.10
235 silly linkStuff jest-cli@0.5.10 has /home/bruno/dev/3rd/molten/node_modules as its parent node_modules
236 verbose linkBins jest-cli@0.5.10
237 verbose link bins [ { jest: './bin/jest.js' },
237 verbose link bins   '/home/bruno/dev/3rd/molten/node_modules/.bin',
237 verbose link bins   false ]
238 verbose linkMans jest-cli@0.5.10
239 verbose rebuildBundles jest-cli@0.5.10
240 verbose rebuildBundles [ '.bin',
240 verbose rebuildBundles   'coffee-script',
240 verbose rebuildBundles   'cover',
240 verbose rebuildBundles   'diff',
240 verbose rebuildBundles   'graceful-fs',
240 verbose rebuildBundles   'istanbul',
240 verbose rebuildBundles   'jasmine-only',
240 verbose rebuildBundles   'jasmine-pit',
240 verbose rebuildBundles   'jsdom',
240 verbose rebuildBundles   'json-stable-stringify',
240 verbose rebuildBundles   'lodash.template',
240 verbose rebuildBundles   'mkdirp',
240 verbose rebuildBundles   'node-haste',
240 verbose rebuildBundles   'node-worker-pool',
240 verbose rebuildBundles   'object-assign',
240 verbose rebuildBundles   'optimist',
240 verbose rebuildBundles   'resolve',
240 verbose rebuildBundles   'sane',
240 verbose rebuildBundles   'through',
240 verbose rebuildBundles   'which' ]
241 silly gentlyRm /home/bruno/dev/3rd/molten/node_modules/.bin/jest is being purged
242 verbose gentlyRm don't care about contents; nuking /home/bruno/dev/3rd/molten/node_modules/.bin/jest
243 silly vacuum-fs purging /home/bruno/dev/3rd/molten/node_modules/.bin/jest
244 silly vacuum-fs quitting because other entries in /home/bruno/dev/3rd/molten/node_modules/.bin
245 info install jest-cli@0.5.10
246 info postinstall jest-cli@0.5.10
247 info install molten@0.1.0
248 info postinstall molten@0.1.0
249 info prepublish molten@0.1.0
250 verbose validateInstall loading /home/bruno/dev/3rd/molten/package.json for validation
251 warn unmet dependency /home/bruno/dev/3rd/molten/node_modules/babel-jest requires babel-core@'^5.5.7' but will load
251 warn unmet dependency /home/bruno/dev/3rd/molten/node_modules/babel-core,
251 warn unmet dependency which is version 6.4.0
252 verbose stack Error: The package history@1.12.5 does not satisfy its siblings' peerDependencies requirements!
252 verbose stack     at /home/bruno/.virtualenvs/nodeenv/lib/node_modules/npm/lib/install.js:125:32
252 verbose stack     at /home/bruno/.virtualenvs/nodeenv/lib/node_modules/npm/lib/install.js:268:7
252 verbose stack     at /home/bruno/.virtualenvs/nodeenv/lib/node_modules/npm/node_modules/read-installed/read-installed.js:142:5
252 verbose stack     at /home/bruno/.virtualenvs/nodeenv/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
252 verbose stack     at cb (/home/bruno/.virtualenvs/nodeenv/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
252 verbose stack     at /home/bruno/.virtualenvs/nodeenv/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
252 verbose stack     at cb (/home/bruno/.virtualenvs/nodeenv/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
252 verbose stack     at /home/bruno/.virtualenvs/nodeenv/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
252 verbose stack     at cb (/home/bruno/.virtualenvs/nodeenv/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
252 verbose stack     at /home/bruno/.virtualenvs/nodeenv/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
253 verbose cwd /home/bruno/dev/3rd/molten
254 error Linux 3.16.0-0.bpo.4-amd64
255 error argv "/home/bruno/.virtualenvs/nodeenv/bin/node" "/home/bruno/.virtualenvs/nodeenv/bin/npm" "install"
256 error node v4.1.2
257 error npm  v2.14.4
258 error code EPEERINVALID
259 error peerinvalid The package history@1.12.5 does not satisfy its siblings' peerDependencies requirements!
259 error peerinvalid Peer react-router@1.0.3 wants history@^1.17.0
260 verbose exit [ 1, true ]
```

**Comment by martinhoefling** [comment]
Interesting, Travis had no problems yesterdays. Can you try out with 5.x version of node?

**Comment by bbinet** [comment]
Yes I will have a look with node 5.x and report back.

**Comment by bbinet** [comment]
I first tried to wipe out my node_modules directory and it did the trick!
Thanks.

**Comment by martinhoefling** [comment]
You're welcome. I switched a lot of dependencies since 0.1.
